version: "3.1"

services:
  postgres:
    image: postgres:10
    restart: always
    container_name: postgres-fin-bot
    environment:
      - POSTGRES_USER=nina
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=fin_db
    ports:
      - "5003:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-fin-bot
    ports:
      - "14268:14268"
      - "16686:16686"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-fin-bot
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9099:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana-fin-bot
    restart: always
    ports:
      - "3000:3000"

  fin-bot:
    build: .
    container_name: fin-bot
    ports:
      - "9176:9176"